import { useEffect, useState } from 'react';
import type { Alert } from '../types/contracts';

const API_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:8000';
export function AlertsPage() {
  const [alerts, setAlerts] = useState<Alert[]>([]); const [selected, setSelected] = useState<Alert | null>(null); const [query, setQuery] = useState('');
  useEffect(() => { void fetch(`${API_URL}/api/alerts?limit=500`).then((response) => response.json()).then(setAlerts); }, []);
  const visible = alerts.filter((alert) => `${alert.alert_id} ${alert.flow_id} ${alert.source_ip} ${alert.destination_ip} ${alert.threat_class}`.toLowerCase().includes(query.toLowerCase()));
  async function changeStatus(id: string, action: 'acknowledge' | 'resolve') { const response = await fetch(`${API_URL}/api/alerts/${id}/${action}`, { method: 'POST' }); const updated = await response.json() as Alert; setAlerts((items) => items.map((item) => item.alert_id === id ? updated : item)); setSelected(updated); }
  return <main className="route-page"><div className="route-heading"><span className="eyebrow">INVESTIGATION / ALERT HISTORY</span><h2>Security alerts</h2><input aria-label="Search alerts" placeholder="Search source, destination, flow or alert ID" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="history-layout"><div className="history-table"><table><thead><tr><th>TIME</th><th>THREAT</th><th>SEVERITY</th><th>SOURCE</th><th>STATUS</th></tr></thead><tbody>{visible.map((alert) => <tr key={alert.alert_id} onClick={() => setSelected(alert)}><td>{new Date(alert.timestamp).toLocaleString()}</td><td>{alert.threat_class}</td><td><span className={`severity ${alert.severity.toLowerCase()}`}>{alert.severity}</span></td><td>{alert.source_ip}</td><td>{alert.status}</td></tr>)}{visible.length === 0 && <tr><td colSpan={5} className="empty-state">No security alerts observed in the current observation window.</td></tr>}</tbody></table></div>{selected && <aside className="detail-drawer"><span className="eyebrow">ALERT DETAIL</span><h3>{selected.threat_class}</h3><div className="detail-score">{selected.confidence_score.toFixed(3)} <small>confidence score</small></div><div className="metadata-list"><span>Severity <b>{selected.severity}</b></span><span>Status <b>{selected.status}</b></span><span>Source <b>{selected.source_ip}</b></span><span>Destination <b>{selected.destination_ip}</b></span><span>Detector <b>{selected.detector}</b></span><span>Version <b>{selected.detector_version}</b></span></div><p>{selected.why_flagged}</p><button onClick={() => void changeStatus(selected.alert_id, selected.status === 'NEW' ? 'acknowledge' : 'resolve')}>{selected.status === 'NEW' ? 'ACKNOWLEDGE' : 'RESOLVE'}</button><pre>{JSON.stringify(selected.evidence, null, 2)}</pre></aside>}</div></main>;
}
