import type { Alert, SystemStatus } from '../types/contracts';
import type { DetectionStatus, DetectorResult } from '../types/detector';
import type { FeatureMetrics, FeatureVector, IngestMetrics, ReplaySource, ReplayStatus } from '../types/ingest';

export const mockAlerts: Alert[] = [
  {
    alert_id: 'alt-9a4f-ddos-syn',
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    flow_id: 'flow-049281-syn-flood',
    threat_class: 'DDOS',
    severity: 'CRITICAL',
    confidence_score: 0.965,
    source_ip: '198.51.100.42',
    destination_ip: '10.0.1.15',
    protocol: 'TCP',
    evidence: {
      syn_packets_per_sec: 14820,
      syn_ack_ratio: 0.002,
      duration_seconds: 4.8,
      source_port_entropy: 7.94,
      mitre_technique: 'T1498 - Network Denial of Service',
      enclave_status: 'Air-gap verified. Zero inbound transmission back to attacker.',
    },
    detector: 'ddos_detector',
    detector_version: '1.2.0',
    model_version: 'xgb-ddos-v1',
    observation_window_ms: 5000,
    alert_type: 'DDOS_SYN_FLOOD',
    subtype: 'HIGH_RATE_SYN_BURST',
    scope: 'flow',
    replay_session_id: 'scenario_02_ddos',
    feature_schema_version: '1.0',
    created_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    first_seen: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    last_seen: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    occurrence_count: 142,
    status: 'NEW',
    evidence_completeness: 0.98,
    correlation_id: 'corr-ddos-cluster-1',
    why_flagged: 'Extreme SYN-to-ACK asymmetry (14,820 SYN/s vs 3 ACK/s) targeting gateway port 443 with randomized high-entropy source ports.',
  },
  {
    alert_id: 'alt-3c81-c2-beacon',
    timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    flow_id: 'flow-038102-beacon-heartbeat',
    threat_class: 'C2_BEACON',
    severity: 'HIGH',
    confidence_score: 0.892,
    source_ip: '10.0.4.88',
    destination_ip: '203.0.113.195',
    protocol: 'TCP',
    evidence: {
      inter_arrival_time_mean_ms: 10014,
      iat_variance: 42.1,
      periodic_regularity_score: 0.94,
      payload_entropy: 5.82,
      destination_port: 8443,
      mitre_technique: 'T1071.001 - Web Protocols Command & Control',
    },
    detector: 'c2_beacon_detector',
    detector_version: '1.1.0',
    model_version: 'rf-c2-v2',
    observation_window_ms: 60000,
    alert_type: 'PERIODIC_C2_HEARTBEAT',
    subtype: 'LOW_JITTER_BEACON',
    scope: 'source_destination_pair',
    replay_session_id: 'scenario_04_c2',
    feature_schema_version: '1.0',
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    first_seen: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    last_seen: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    occurrence_count: 28,
    status: 'ACKNOWLEDGED',
    evidence_completeness: 0.94,
    correlation_id: 'corr-apt29-cluster',
    why_flagged: 'Periodic telemetry pattern detected: 28 consecutive outbound connections at strictly fixed 10.0s intervals with near-zero jitter (variance 42ms).',
  },
  {
    alert_id: 'alt-5e29-dns-tunnel',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    flow_id: 'flow-091244-dns-exfil',
    threat_class: 'DGA_DNS_TUNNEL',
    severity: 'CRITICAL',
    confidence_score: 0.978,
    source_ip: '10.0.2.14',
    destination_ip: '1.1.1.1',
    protocol: 'UDP',
    evidence: {
      shannon_entropy: 4.88,
      query_length_mean: 62.4,
      distinct_subdomains_10m: 340,
      record_type: 'TXT',
      mitre_technique: 'T1071.004 - DNS Tunneling',
    },
    detector: 'dns_tunnel_detector',
    detector_version: '1.4.0',
    model_version: 'bayes-dga-v1',
    observation_window_ms: 10000,
    alert_type: 'DNS_COVERT_CHANNEL',
    subtype: 'HIGH_ENTROPY_TXT_EXFILTRATION',
    scope: 'source_ip',
    replay_session_id: 'scenario_07_dns_tunnel',
    feature_schema_version: '1.0',
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    first_seen: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    last_seen: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    occurrence_count: 340,
    status: 'NEW',
    evidence_completeness: 0.99,
    correlation_id: 'corr-dns-exfil-01',
    why_flagged: 'High-frequency encoded subdomains with Shannon entropy 4.88 querying apex domain xf-tunnel.secops-internal.org.',
  },
  {
    alert_id: 'alt-7f12-portscan',
    timestamp: new Date(Date.now() - 1000 * 60 * 24).toISOString(),
    flow_id: 'flow-018241-syn-recon',
    threat_class: 'RECON',
    severity: 'MEDIUM',
    confidence_score: 0.814,
    source_ip: '192.168.10.155',
    destination_ip: '10.0.0.0/24',
    protocol: 'TCP',
    evidence: {
      distinct_dst_ports_seen: 450,
      scan_rate_ports_per_sec: 180,
      failed_handshake_ratio: 0.97,
      tcp_flags: 'SYN',
      mitre_technique: 'T1046 - Network Service Discovery',
    },
    detector: 'recon_detector',
    detector_version: '1.0.0',
    model_version: null,
    observation_window_ms: 15000,
    alert_type: 'HORIZONTAL_SYN_SWEEP',
    subtype: 'PORT_SWEEP',
    scope: 'source_ip',
    replay_session_id: 'scenario_03_recon',
    feature_schema_version: '1.0',
    created_at: new Date(Date.now() - 1000 * 60 * 24).toISOString(),
    first_seen: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    last_seen: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    occurrence_count: 85,
    status: 'RESOLVED',
    evidence_completeness: 0.91,
    correlation_id: null,
    why_flagged: 'Horizontal network scan probed 450 unique destination ports across 10.0.0.0/24 within 3 seconds with 97% unacknowledged SYNs.',
  },
  {
    alert_id: 'alt-1b48-exfil-vol',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    flow_id: 'flow-077123-outbound-spike',
    threat_class: 'DATA_EXFILTRATION',
    severity: 'HIGH',
    confidence_score: 0.912,
    source_ip: '10.0.3.50',
    destination_ip: '198.51.100.220',
    protocol: 'TCP',
    evidence: {
      bytes_out_mb: 840,
      bytes_in_mb: 2.1,
      out_in_ratio: 400.0,
      duration_seconds: 124,
      mitre_technique: 'T1041 - Exfiltration Over C2 Channel',
    },
    detector: 'exfiltration_detector',
    detector_version: '1.1.0',
    model_version: 'iso-forest-v1',
    observation_window_ms: 30000,
    alert_type: 'VOLUME_SPIKE_EXFILTRATION',
    subtype: 'ASYMMETRIC_EGRESS',
    scope: 'flow',
    replay_session_id: 'scenario_05_exfil',
    feature_schema_version: '1.0',
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    first_seen: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    last_seen: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    occurrence_count: 14,
    status: 'ACKNOWLEDGED',
    evidence_completeness: 0.95,
    correlation_id: 'corr-db-leak-2',
    why_flagged: 'Extreme egress volume: 840 MB transferred outbound to unclassified external IP over port 443 with 400:1 upload-to-download ratio.',
  },
  {
    alert_id: 'alt-4d90-tls-fingerprint',
    timestamp: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    flow_id: 'flow-049811-suspicious-ja3',
    threat_class: 'ENCRYPTED_MALWARE',
    severity: 'MEDIUM',
    confidence_score: 0.835,
    source_ip: '10.0.5.12',
    destination_ip: '185.220.101.5',
    protocol: 'TLS',
    evidence: {
      ja3_hash: '51c64c77e60f3980eea90869b68c58a8',
      sni: 'update-check-telemetry.ru',
      tls_version: 'TLS 1.2',
      cipher_count: 4,
      mitre_technique: 'T1573 - Encrypted Channel',
    },
    detector: 'encrypted_traffic_detector',
    detector_version: '1.2.0',
    model_version: 'ja3-threat-intel',
    observation_window_ms: 5000,
    alert_type: 'MALICIOUS_TLS_METADATA',
    subtype: 'JA3_BLACKLIST_MATCH',
    scope: 'flow',
    replay_session_id: 'scenario_08_encrypted',
    feature_schema_version: '1.0',
    created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    first_seen: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    last_seen: new Date(Date.now() - 1000 * 60 * 48).toISOString(),
    occurrence_count: 3,
    status: 'RESOLVED',
    evidence_completeness: 0.9,
    correlation_id: null,
    why_flagged: 'JA3 client fingerprint matches TrickBot malware profile without decrypting TLS session; non-standard cipher order observed.',
  },
];

export const mockSystemStatus: SystemStatus = {
  service_status: 'healthy',
  ingest_status: 'running',
  ingest_mode: 'passive_unidirectional',
  receive_only: true,
  payload_decryption: false,
  return_path: false,
  active_detectors: ['ddos', 'recon', 'c2_beacon', 'dns_tunnel', 'exfiltration', 'encrypted_traffic'],
  flows_per_second: 428.5,
  throughput_mbps: 34.2,
  alerts_total: 6,
  last_event_timestamp: new Date().toISOString(),
};

export const mockIngestMetrics: IngestMetrics = {
  packets_seen: 184520,
  flows_emitted: 24890,
  flows_per_second: 428.5,
  bytes_per_second: 4482910,
  throughput_mbps: 35.86,
  active_flows: 1420,
  events_dropped: 0,
  malformed_packets: 0,
  unsupported_packets: 0,
  ingest_latency_ms: 1.42,
  queue_size: 42,
  queue_maxsize: 10000,
};

export const mockFeatureMetrics: FeatureMetrics = {
  feature_engine_status: 'running',
  feature_vectors_per_sec: 425.0,
  feature_processing_latency_ms: 0.88,
  feature_processing_latency_max_ms: 2.14,
  feature_events_dropped: 0,
  feature_errors: 0,
  active_flow_state: 1420,
  active_source_state: 380,
  active_pair_state: 890,
  recent_feature_vectors: 24890,
  feature_queue_size: 18,
  feature_queue_maxsize: 10000,
  window_count: 4,
};

export const mockDetectionStatus: DetectionStatus = {
  active_detectors: ['ddos', 'recon', 'c2_beacon', 'dns_tunnel', 'exfiltration', 'encrypted_traffic'],
  detector_count: 6,
  detector_results_emitted: 3482,
  detector_results_dropped: 0,
  average_latency_ms: 0.64,
  errors: 0,
  detectors: [
    { name: 'ddos_detector', enabled: true, threat_class: 'DDOS', version: '1.2.0', status: 'ACTIVE', results_emitted: 142, errors: 0, average_latency_ms: 0.32, scopes: ['flow', 'source_ip'] },
    { name: 'recon_detector', enabled: true, threat_class: 'RECON', version: '1.0.0', status: 'ACTIVE', results_emitted: 85, errors: 0, average_latency_ms: 0.41, scopes: ['source_ip'] },
    { name: 'c2_beacon_detector', enabled: true, threat_class: 'C2_BEACON', version: '1.1.0', status: 'ACTIVE', results_emitted: 28, errors: 0, average_latency_ms: 0.82, scopes: ['source_destination_pair'] },
    { name: 'dns_tunnel_detector', enabled: true, threat_class: 'DGA_DNS_TUNNEL', version: '1.4.0', status: 'ACTIVE', results_emitted: 340, errors: 0, average_latency_ms: 0.55, scopes: ['source_ip', 'domain'] },
    { name: 'exfiltration_detector', enabled: true, threat_class: 'DATA_EXFILTRATION', version: '1.1.0', status: 'ACTIVE', results_emitted: 14, errors: 0, average_latency_ms: 0.48, scopes: ['flow'] },
    { name: 'encrypted_traffic_detector', enabled: true, threat_class: 'ENCRYPTED_MALWARE', version: '1.2.0', status: 'ACTIVE', results_emitted: 3, errors: 0, average_latency_ms: 0.68, scopes: ['flow'] },
  ],
};

export const defaultReplaySources: ReplaySource[] = [
  { name: '09_mixed_demo.jsonl', path: 'data/raw/scenarios/09_mixed_demo.jsonl', source_type: 'jsonl', size_bytes: 10676 },
  { name: '02_ddos.jsonl', path: 'data/raw/scenarios/02_ddos.jsonl', source_type: 'jsonl', size_bytes: 2208 },
  { name: '03_recon.jsonl', path: 'data/raw/scenarios/03_recon.jsonl', source_type: 'jsonl', size_bytes: 2184 },
  { name: '04_c2.jsonl', path: 'data/raw/scenarios/04_c2.jsonl', source_type: 'jsonl', size_bytes: 1890 },
  { name: '05_exfil.jsonl', path: 'data/raw/scenarios/05_exfil.jsonl', source_type: 'jsonl', size_bytes: 267 },
  { name: '06_dga.jsonl', path: 'data/raw/scenarios/06_dga.jsonl', source_type: 'jsonl', size_bytes: 321 },
  { name: '07_dns_tunnel.jsonl', path: 'data/raw/scenarios/07_dns_tunnel.jsonl', source_type: 'jsonl', size_bytes: 2070 },
  { name: '08_encrypted.jsonl', path: 'data/raw/scenarios/08_encrypted.jsonl', source_type: 'jsonl', size_bytes: 406 },
  { name: 'synthetic_benchmark.pcap', path: 'data/raw/synthetic_benchmark.pcap', source_type: 'pcap', size_bytes: 236656 },
  { name: 'synthetic_fixture.pcap', path: 'data/raw/synthetic_fixture.pcap', source_type: 'pcap', size_bytes: 5004 },
];

export const mockFeatureVector: FeatureVector = {
  feature_id: 'fv-demo-001',
  flow_id: 'flow-demo-current',
  timestamp: new Date().toISOString(),
  window_start: null,
  window_end: null,
  scope: 'flow',
  source_type: 'jsonl',
  groups: {},
  availability: { flow_duration_ms: true, byte_entropy: true },
  feature_schema_version: '1.0',
  values: {
    flow_duration_ms: 4820,
    packets_per_second: 3080.5,
    bytes_per_second: 2489100,
    byte_entropy: 7.82,
    tcp_syn_count: 14820,
    tcp_ack_count: 4,
    tcp_rst_count: 0,
    inter_arrival_time_mean_ms: 0.32,
    inter_arrival_time_std_ms: 0.08,
    dns_query_length: 64,
    dns_subdomain_entropy: 4.88,
    ja3_fingerprint_hash: '51c64c77e60f3980eea90869b68c58a8',
    source_ip: '198.51.100.42',
    destination_ip: '10.0.1.15',
    protocol: 'TCP',
  },
};
